// #define CONFIG_IDF_TARGET_ESP32 1
// #define CONFIG_IDF_TARGET_ESP32S2 1
#define CONFIG_IDF_TARGET_ESP32S3 1

#define CONFIG_APPTRACE_DEST_JTAG 1
#define CONFIG_APPTRACE_ENABLE 1
#define CONFIG_APPTRACE_LOCK_ENABLE 1
#define CONFIG_APPTRACE_ONPANIC_HOST_FLUSH_TMO -1
#define CONFIG_APPTRACE_POSTMORTEM_FLUSH_THRESH 0
#define CONFIG_APPTRACE_PENDING_DATA_SIZE_MAX 0
#define CONFIG_APPTRACE_GCOV_ENABLE 1

